### ISSUE TITLE
reservation display

### ISSUE THREAD

**Issue by babasselegrand** [pluginsGLPI/room#29]
Hello,
I would like to know if it is possible to display the purpose of the meeting rather than the name of the person who reserved the room.

Thank you for your help

********************
Bonjour,
Je souhaiterai savoir s'il est possible d'afficher l'objet de la réunion plutot que le nom de la personne ayant reserved la salle.

Merci de votre aide

**Comment by C-Duv** [comment]
The reservation occupation calendar is handled by GLPI not the room plugin, if what you want is to display "Comments" in the calendar instead of the reservation author I guess you have to ask GLPI's core for it.

I am not sure it will be useful though: usually, you just want to know who have the "item" you wanted, not why.

Note that the "Comments" field is available by hovering the reservation box (I guess you already knew that but just in case...).

**Comment by babasselegrand** [comment]
yes i see that.
thaks a lot
